### ISSUE TITLE
error: python interpreter not found, but i've installed python

### ISSUE THREAD

**Issue by wangruitang** [google/tcmalloc#139]
hi, there~
i'm trying to test tcmalloc with bazel, but it fails with an error: python interpreter not found.
Actually, i've installed python and i can use it in terminal.
i'm using Windows 10 21H2.
```
PS C:\Users\user\source\repos\tcmalloc> python
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
PS C:\Users\user\source\repos\tcmalloc> bazel test //tcmalloc/...
INFO: Repository fuzzing_py_deps instantiated at:
  C:/users/user/source/repos/tcmalloc/WORKSPACE:100:19: in <toplevel>
  C:/users/user/_bazel_user/wvm6tfml/external/rules_fuzzing/fuzzing/init.bzl:23:16: in rules_fuzzing_init
  C:/users/user/_bazel_user/wvm6tfml/external/rules_python/python/pip.bzl:53:19: in pip_install
Repository rule pip_repository defined at:
  C:/users/user/_bazel_user/wvm6tfml/external/rules_python/python/pip_install/pip_repository.bzl:67:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'fuzzing_py_deps':
   Traceback (most recent call last):
        File "C:/users/user/_bazel_user/wvm6tfml/external/rules_python/python/pip_install/pip_repository.bzl", line 14, column 17, in _pip_repository_impl
                fail("python interpreter not found")
Error in fail: python interpreter not found
ERROR: C:/users/user/source/repos/tcmalloc/WORKSPACE:100:19: fetching pip_repository rule //external:fuzzing_py_deps: Traceback (most recent call last):
        File "C:/users/user/_bazel_user/wvm6tfml/external/rules_python/python/pip_install/pip_repository.bzl", line 14, column 17, in _pip_repository_impl
                fail("python interpreter not found")
Error in fail: python interpreter not found
INFO: Repository remote_coverage_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:3:13: in <toplevel>
Repository rule http_archive defined at:
  C:/users/user/_bazel_user/wvm6tfml/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository rules_pkg instantiated at:
  C:/users/user/source/repos/tcmalloc/WORKSPACE:69:14: in <toplevel>
  C:/users/user/_bazel_user/wvm6tfml/external/com_google_protobuf/protobuf_deps.bzl:78:21: in protobuf_deps
Repository rule http_archive defined at:
  C:/users/user/_bazel_user/wvm6tfml/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
INFO: Repository rules_java instantiated at:
  C:/users/user/source/repos/tcmalloc/WORKSPACE:69:14: in <toplevel>
  C:/users/user/_bazel_user/wvm6tfml/external/com_google_protobuf/protobuf_deps.bzl:47:21: in protobuf_deps
Repository rule http_archive defined at:
  C:/users/user/_bazel_user/wvm6tfml/external/bazel_tools/tools/build_defs/repo/http.bzl:353:31: in <toplevel>
ERROR: C:/users/user/source/repos/tcmalloc/tcmalloc/internal/BUILD:475:13: //tcmalloc/internal:numa_fuzz_corpus depends on @rules_fuzzing//fuzzing/tools:make_corpus_dir in repository @rules_fuzzing which failed to fetch. no such package '@fuzzing_py_deps//': python interpreter not found
ERROR: Analysis of target '//tcmalloc/internal:numa_fuzz' failed; build aborted:
INFO: Elapsed time: 0.882s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: @rules_fuzzing//fuzzing/tools ... (3 packages)
    Fetching https://mirror.bazel.build/.../bazelbuild/rules_pkg/releases/download/0.5.1/rules_pkg-0.5.1.tar.gz
    Fetching https://github.com/bazelbuild/rules_java/archive/981f06c3d2bd10225e85209904090eb7b5fb26bd.tar.gz
PS C:\Users\user\source\repos\tcmalloc> 
```

**Comment by patrickxia** [comment]
This seems like you're probably missing a binary called `python3`.

https://github.com/bazelbuild/rules_python/issues/563

**Comment by wangruitang** [comment]
> This seems like you're probably missing a binary called `python3`.
> 
> [bazelbuild/rules_python#563](https://github.com/bazelbuild/rules_python/issues/563)

i renamed "python.exe" to "python3.exe" and it works!
