### ISSUE TITLE
unable to capture stacktrace with gcc __builtin options

### ISSUE THREAD

**Issue by bkannadassan** [google/tcmalloc#23]
```
struct stack_frame {
        struct stack_frame *prev;
        void *return_addr;
} __attribute__((packed));
typedef struct stack_frame stack_frame;

void backtrace_from_fp(void **buf, int size)
{
/*
        int i;
        stack_frame *fp;

        __asm__ __volatile__("movq %%rbp, %[fp]" :  [fp] "=r" (fp));

        for(i = 0; i < size && fp != NULL; fp = fp->prev, i++)
                buf[i] = fp->return_addr;
*/
                buf[0] =  __builtin_return_address (0);
                buf[2] =  __builtin_return_address (1);
}
```
My code which uses malloc
```
#include <malloc.h>
void f3()
{
  malloc(10);
}
void f2()
{
}
void f1()
{
}
void f()
{
}
main()
{
  f();
}

g++ -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -lpthread pop.c .libs/libtcmalloc_and_profiler.a

```
Above is how I built with static library.

I do get crash as below..

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000041f417 in backtrace_from_fp (size=10, buf=<optimized out>) at src/tcmalloc.cc:1914
1914                    buf[2] =  __builtin_return_address (1);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-196.el7_4.2.x86_64 libgcc-4.8.5-36.el7_6.2.x86_64 libstdc++-4.8.5-36.el7_6.2.x86_64
(gdb) bt
#0  0x000000000041f417 in backtrace_from_fp (size=10, buf=<optimized out>) at src/tcmalloc.cc:1914
#1  tc_malloc (size=size@entry=1) at src/tcmalloc.cc:1924
#2  0x00000000004051d6 in TCMallocGuard::TCMallocGuard (this=<optimized out>) at src/tcmalloc.cc:1121
#3  0x0000000000403498 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at src/tcmalloc.cc:1153
#4  _GLOBAL__sub_I__ZN61FLAG__namespace_do_not_use_directly_use_DECLARE_int64_instead43FLAGS_tcmalloc_large_alloc_report_thresholdE ()
    at src/tcmalloc.cc:2319
#5  0x000000000041eb5d in __libc_csu_init ()
#6  0x00007ffff6ffeb95 in __libc_start_main () from /lib64/libc.so.6
#7  0x0000000000403bf8 in _start ()
(gdb)
```
Any help on the same ?.

rgds
Balaji Kamal Kannadassan

**Comment by ckennelly** [comment]
This looks like https://github.com/gperftools/gperftools.  The symbols referenced (`_GLOBAL__sub_I__ZN61FLAG__namespace_do_not_use_directly_use_DECLARE_int64_instead43FLAGS_tcmalloc_large_alloc_report_thresholdE`) do not appear in this repository.
